swagger: '2.0'
info:
  title: topicos-api-gateway
  description: Api de gateway para gestionar las rutas de los microservicios
  version: 1.0.0

schemes:
  - https

paths:
  /usuario/listar:
    get:
      operationId: listarUsuarios
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/listar_usuarios
      responses:
        '200':
          description: OK

  /usuario/crear:
    post:
      operationId: crearUsuario
      x-google-backend:
        address: https://southamerica-east1-TU_PROYECTO.cloudfunctions.net/crear_usuario
      responses:
        '200':
          description: OK
  
  /usuario/obtener/{id}:
    get:
      operationId: obtenerUsuario
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/obtener_usuario
      responses:
        '200':
          description: OK

  /compra/crear:
    post:
      operationId: crearCompra
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_compra
      responses:
        '201':
          description: Created
  
  /detalle_compra/crear:
    post:
      operationId: crearDetalleCompra
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_detalle_compra
      responses:
        '201':
          description: Created

  /inventario/crear:
    post:
      operationId: crearProducto
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_producto
      responses:
        '201':
          description: Created
  
  /inventario/aumentar_stock:
    put:
      operationId: aumentarStockProducto
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/aumentar_stock
      responses:
        '200':
          description: OK
          
  /inventario/disminuir_stock:
    put:
      operationId: disminuirStockProducto
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/disminuir_stock
      responses:
        '200':
          description: OK      

  /venta/crear:
    post:
      operationId: crearVenta
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_venta
      responses:
        '200':
          description: OK

  /venta/crear_detalle_venta:
    put:
      operationId: crearDetalleVenta
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_detalle_venta
      responses:
        '200':
          description: OK          
  
  /venta/anular_detalle_venta:
    put:
      operationId: anularDetalleVenta
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/anular_detalle_venta
      responses:
        '200':
          description: OK          