swagger: '2.0'
info:
  title: topicos-api-gateway
  description: Api de gateway para gestionar las rutas de los microservicios
  version: 1.0.0

schemes:
  - https

paths:
  /usuario/listar:
    get:
      operationId: listarUsuarios
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/listar_usuarios
      responses:
        '200':
          description: OK

  /usuario/crear:
    post:
      operationId: crearUsuario
      x-google-backend:
        address: https://southamerica-east1-TU_PROYECTO.cloudfunctions.net/crear_usuario
      responses:
        '200':
          description: OK
  
  /usuario/obtener/{id}:
    get:
      operationId: obtenerUsuario
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/obtener_usuario
      responses:
        '200':
          description: OK


  /inventario/obtenerproducto/{id}:
    get:
      operationId: obtenerProducto
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/obtener_producto
      responses:
        '200':
          description: Producto obtenido

  /compras/crear:
    post:
      operationId: crearCompra
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_compra
      responses:
        '201':
          description: Compra creada

  /compras/crear_detalle:
    post:
      operationId: crearDetalleCompra
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/crear_detallecompra
      responses:
        '201':
          description: Detalle de compra creado

  /compras/anular_detalle:
    post:
      operationId: anularDetalleCompra
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/anular_detallecompra
      responses:
        '201':
          description: Detalle de compra anulado

  /compras/anular_compra:
    post:
      operationId: anularCompra
      x-google-backend:
        address: https://southamerica-east1-gen-lang-client-0878332190.cloudfunctions.net/anular_compra
      responses:
        '201':
          description: Compra anulada          